"""Données de référence pour Rfill : glossaires de catégorisation, codes de surface, libellés et notes réglementaires."""

glossary_surf = {'surfaces_utilisables': {'bureaux / plateaux': ['bureau',
                                                 'open space',
                                                 'plateau bureaux',
                                                 'reprographie',
                                                 'accueil',
                                                 'd.a.b.',
                                                 'surface de vente',
                                                 'bureaux'],
                          'réserves / archives': ['réserve', 'archives', 'stockage'],
                          'locaux sociaux': ['salle de repos',
                                             'salle de restaurant',
                                             'self service',
                                             'salle de gym',
                                             'salle de musculation',
                                             'vestiaire'],
                          'sanitaires': ['sanitaires', 'w.c.', 'douche', 'sanitaire'],
                          'circulations / dégagements': ["hall d'entrée", 'entrée', 'sas', 'palier', 'dgt'],
                          'locaux techniques': ['local c.t.a.',
                                                'onduleur',
                                                'local sprinkler',
                                                'r.i.a.',
                                                'l.t.g.',
                                                'l.t.p.',
                                                'local serveur'],
                          'locaux techniques secondaires': ['local ménage', 'local poubelle'],
                          'espaces extérieurs / annexes': ['terrasse', 'balcons', 'loggias', 'auvent'],
                          'stationnements': ['parkings', 'rampes'],
                          'surfaces non exploitables': ['ht<1.80m'],
                          'surfaces spécifiques': ['cuisine', 'salle de réunion', "salle d'attente"],
                          'Surfaces <1.80m': ['ht>1.80m']},
 'sho': {'surfaces structurelles / non exploitables': ['shob avant déduction',
                                                       'surface brute',
                                                       'ht<1.80m',
                                                       'combles non aménageables',
                                                       'sous-sol non aménageable'],
         'locaux techniques (larges)': ['locaux techniques',
                                        'locaux techniques généraux',
                                        'locaux techniques particuliers',
                                        'caves / annexes'],
         'stationnements / infrastructures': ['parkings', 'rampes', 'stationnements'],
         'circulations générales bâtiment': ['dégagements', 'circulations', 'entrée', 'hall'],
         'enveloppe / extérieur': ['terrasses', 'balcons', 'loggias', 'toitures-terrasses'],
         'vide / structure': ['vides techniques', 'trémies']},
 'sdp': {'surfaces principales de bâtiment (brut réglementaire)': ['sdp avant déduction',
                                                                   'surface de plancher',
                                                                   'surface brute de plancher'],
         'espaces de bureaux (base administrative)': ['bureaux',
                                                      'plateaux bureaux',
                                                      'open space',
                                                      'accueil',
                                                      'reprographie'],
         'locaux fonctionnels intégrés': ['salle de réunion',
                                          "salle d'attente",
                                          'cuisine (si intégrée programme tertiaire)',
                                          'salle de repos'],
         'locaux sanitaires (inclus réglementaire)': ['sanitaires', 'w.c.', 'douche'],
         'circulations intégrées sdp': ["hall d'entrée", 'entrée', 'sas', 'dégagements', 'palier', 'circulations'],
         'stockage / annexes intégrées': ['réserve', 'archives', 'local ménage', 'stockage'],
         'locaux techniques inclus (selon réglementation)': ['local serveur',
                                                             'local c.t.a.',
                                                             'onduleur',
                                                             'local sprinkler',
                                                             'r.i.a.',
                                                             'd.a.b.']}}

denom_surf = {'SUB': 'surfaces_utilisables',
 'SU': 'surfaces_utilisables',
 'SUBL': 'surfaces_utilisables',
 'SUN': 'surfaces_utilisables',
 'TAX': 'surfaces_utilisables',
 'TSB': 'surfaces_utilisables',
 'SHO': 'sho',
 'SDP': 'sdp',
 'GLA': 'surfaces_utilisables'}

real_su_name = {'SUB': 'SURFACES UTILES BRUTES (SUB*)',
 'SU': 'SURFACES UTILES (SU*)',
 'SUBL': 'SURFACES UTILES BRUTES LOCATIVES (SUBL*)',
 'SUN': 'SURFACES UTILES NETTES (SUN*)',
 'SDP': 'SURFACES DE PLANCHER (SDP*)',
 'SHO': 'SURFACES HORS OEUVRE (SHO*)',
 'GLA': 'SURFACES GLOBALES (GLA*)',
 'TAX': 'SYNTHESE DES SURFACES RÉELLES* (Art. 324 M ou Z Annexe III du CGI)',
 'TSB': 'TABLEAU SURFACES BRUTES (TSB*)'}

superficie_names = {
    'SDP': ['(1)', '(2)', '(3)', '(4)', '(5)', '(6)', '(7)', '(8)', '(9)', '(10)'],
    'SU':  ['Superficies utiles', 'Superficies annexes'],
    'TAX': ['Superficies réelles'],
    'SUB': ['Superficies utiles brutes privatives',
            'Superficies utiles brutes à usage commun',
            'Superficies annexes'],
    'SUN': ['Superficies utiles NETTES', 'Superficies déduites de la SUB'],
    'SUBL': ['Superficies utiles brutes privatives',
             'Superficies utiles brutes à usage commun',
             'Superficies annexes'],
    'SHO': ['Détermination de la S.H.O.B.', 'Détermination de la S.H.O.N.'],
    'GLA': ['Superficies globales'],
    'TSB': ['Superficies brutes'],
}

predefined_cats = {
    'SHO': [
        'Surface avant déductions',
        'Vides et trémies',
        'Total S.H.O. Brute (en m²)',
        'Sous-sol et combles avec h plafond < 1.80m',
        'Sous-sol et combles non aménageables',
        'Locaux techniques en sous-sol et combles',
        'Non-Clos au Rdc',
        'Balcons/Loggias',
        'Toitures-terrasses',
        'Stationnements',
        'Déductions relatives aux exploitations agricoles',
        'Habitation : 5%[(SHOB-a+b+c)]',
        'Déductions relatives aux refections d\'immeubles d\'habitation',
    ],
    'SUBL': [
        'Bureaux / Plateaux',
        'Réserves / Archives',
        'Locaux serveurs',
        'Locaux sociaux',
        'Sanitaires',
        'Dégagements / Circulations / Entrée',
        'Locaux techniques particuliers',
        'Total SUB',
        'Palier',
        'Commun particulier',
        'Total SUB à usage commun',
        'Surfaces < 1.80 m',
        'Locaux techniques généraux**',
        'Parkings / Rampes',
    ],
    'SUN': [
        'Bureaux',
        'Salles de réunion',
        'Annexes de travail',
        'Total SUN',
        'Circulations horizontales',
        'Services généraux',
        'Logements',
        'Services sociaux',
        'Surfaces NON transformable en bureau **',
    ],
    'TAX': [
        'Bureaux',
        'Chambres',
        'Réserves Archives',
        'Locaux serveurs',
        'Locaux sociaux',
        'Sanitaires',
        'Dégagements / Circulations / Entrée',
        'Locaux techniques particuliers',
        'Surfaces < 1.80 m',
        'Locaux techniques généraux**',
        'Parkings / Rampes',
        'Terrasses / Balcons / Courette',
    ],
    'SDP': [
        'Planchers avant déductions',
        'Vides Gaines Techniques',
        'Surfaces avec h < 1.80 m',
        'Total TA',
        'Stationnements',
        'Combles non aménageables',
        'Locaux techniques',
        'Caves/annexes',
        'Déduction 10% (Habitation)',
    ],
}

nota_surf = {
    'SDP': [
        "*SDP suivant Art. R. 111-22 du code de l'urbanisme",
        "(1) Somme des surfaces de planchers de chaque niveau clos et couvert, calculées à partir du nu intérieur des murs, sans prendre en compte l'épaisseur des murs entourant les embrasures des portes et fenêtres donnant sur l'extérieur.",
        "(2) Vides et trémies afférentes aux ascenseurs et escaliers.",
        "(3) Surfaces de planchers d'une hauteur sous plafond inférieure ou égale à 1m80.",
        "(4) Surface taxable assiette de la Taxe d'Aménagement (TA) = colonne 1 - colonnes (2 - 3).",
        "(5) Surfaces des planchers aménagés en vue du stationnement des véhicules motorisés ou non, y compris les rampes d'accès et les aires de manoeuvres.",
        "(6) Surfaces des planchers des combles non aménageables pour l'habitation ou pour des activités à caractère professionnel, artisanal, industriel ou commercial.",
        "(7) Surfaces des planchers des locaux techniques nécessaires au fonctionnement d'un groupe de bâtiments ou d'un immeuble autre qu'une maison individuelle, y compris les locaux de stockage des déchets.",
        "(8) Surfaces de planchers des caves ou celliers, annexes à des logements, dès lors que ces locaux sont desservis uniquement par une partie commune.",
        "(9) Surface égale à 10% des surfaces des planchers affectés à l'habitation telle qu'elles résultent le cas échéant de l'application des déductions précédentes, dès lors que les logements sont desservis par des parties intérieures communes.",
        "(10) Surface de Plancher (SDP) Totale = colonne 4 - colonnes (5 - 6 - 7 - 8 - 9).",
    ],
    'SU': [
        "* : Surfaces Utiles pièce à pièce (surface conventionnelle étudiée à partir de la surface de plancher)",
        "** : servant au fonctionnement de l'immeuble",
    ],
    'TAX': [
        "* : Surfaces Réelles pièce à pièce (mesurée au sol, entre murs ou séparations)",
        "** : servant au fonctionnement de l'immeuble",
    ],
    'SUB': [
        "* : SUB telles que décrites dans la charte de l'expertise en évaluation immobilière (2015 - 6ème édition)",
        "** : servant au fonctionnement de l'immeuble",
        'Surfaces "plateau bureaux" ne tenant pas compte des cloisons légères sauf celles délimitant deux lots ou les circulations verticales et les sanitaires.',
    ],
    'SUN': [
        "* : SUN telles que décrites dans la charte de l'expertise en évaluation immobilière (2017 - 5ème édition) - surfaces utile réservée à l'espace de travail",
        "** : Sont non transformable en bureau - exemples : Hall, sanitaires, vestiaires…",
        'Surfaces "plateau bureaux" ne tenant pas compte des cloisons légères sauf celles délimitant deux lots ou les circulations verticales et les sanitaires.',
    ],
    'SUBL': [
        "* : SUBL selon définition fournie par le client",
        "** : servant au fonctionnement de l'immeuble",
        'Surfaces "plateau bureaux" ne tenant pas compte des cloisons légères sauf celles délimitant deux lots ou les circulations verticales et les sanitaires.',
    ],
    'SHO': [
        "a) Sont déduites les surfaces de plancher hors oeuvre des combles et des sous-sols non aménageables pour l'habitation ou pour des activités à caractère professionnel, artisanal, industriel ou commercial.",
        "b) Sont déduites les surfaces de plancher hors oeuvre des toitures-terrasses, des balcons, des loggias, ainsi que des surfaces non closes situées au rez-de-chaussée.",
        "c) Sont déduites les surfaces de plancher hors oeuvre des bâtiments ou des parties de bâtiments aménagés en vue du stationnement des véhicules.",
        "d) Sont déduites les surfaces de plancher hors oeuvre des bâtiments affectés au logement des récoltes, des animaux ou du matériel agricole ainsi que les serres de production.",
        "e) Est déduite une surface égale à 5 p. 100 des surfaces hors oeuvre affectées à l'habitation telles qu'elles résultent, le cas échéant, de l'application des a, b et c ci-dessus.",
        "f) Sont également déduites de la surface hors oeuvre dans le cas de la réfection d'un immeuble à usage d'habitation et dans la limite de cinq mètres carrés par logement les surfaces de plancher affectées à la réalisation d'ouvrages tendant à l'amélioration de l'hygiène des locaux et celles résultant de la fermeture de balcons, loggias et surfaces non closes situées en rez-de-chaussée.",
        "Pour le calcul des superficies de planchers hors oeuvre brutes et nettes, il est tenu compte le cas échéant du décret n°2009-1247 du 16 octobre 2009 relatif aux surfaces de planchers supplémentaires nécessaires à l'aménagement d'une construction existante en vue d'améliorer son isolation thermique et acoustique.",
    ],
}
