glossary_surf = {'surfaces_utilisables': {'bureaux / plateaux': ['bureau',
                                                 'open space',
                                                 'plateau bureaux',
                                                 'reprographie',
                                                 'accueil',
                                                 'd.a.b.',
                                                 'surface de vente',
                                                 'bureaux'],
                          'réserves / archives': ['réserve', 'archives', 'stockage'],
                          'locaux sociaux': ['salle de repos',
                                             'salle de restaurant',
                                             'self service',
                                             'salle de gym',
                                             'salle de musculation',
                                             'vestiaire'],
                          'sanitaires': ['sanitaires', 'w.c.', 'douche', 'sanitaire'],
                          'circulations / dégagements': ["hall d'entrée", 'entrée', 'sas', 'palier', 'dgt'],
                          'locaux techniques': ['local c.t.a.',
                                                'onduleur',
                                                'local sprinkler',
                                                'r.i.a.',
                                                'l.t.g.',
                                                'l.t.p.',
                                                'local serveur'],
                          'locaux techniques secondaires': ['local ménage', 'local poubelle'],
                          'espaces extérieurs / annexes': ['terrasse', 'balcons', 'loggias', 'auvent'],
                          'stationnements': ['parkings', 'rampes'],
                          'surfaces non exploitables': ['ht<1.80m'],
                          'surfaces spécifiques': ['cuisine', 'salle de réunion', "salle d'attente"],
                          'Surfaces <1.80m': ['ht>1.80m']},
 'sho': {'surfaces structurelles / non exploitables': ['shob avant déduction',
                                                       'surface brute',
                                                       'ht<1.80m',
                                                       'combles non aménageables',
                                                       'sous-sol non aménageable'],
         'locaux techniques (larges)': ['locaux techniques',
                                        'locaux techniques généraux',
                                        'locaux techniques particuliers',
                                        'caves / annexes'],
         'stationnements / infrastructures': ['parkings', 'rampes', 'stationnements'],
         'circulations générales bâtiment': ['dégagements', 'circulations', 'entrée', 'hall'],
         'enveloppe / extérieur': ['terrasses', 'balcons', 'loggias', 'toitures-terrasses'],
         'vide / structure': ['vides techniques', 'trémies']},
 'spd': {'surfaces principales de bâtiment (brut réglementaire)': ['sdp avant déduction',
                                                                   'surface de plancher',
                                                                   'surface brute de plancher'],
         'espaces de bureaux (base administrative)': ['bureaux',
                                                      'plateaux bureaux',
                                                      'open space',
                                                      'accueil',
                                                      'reprographie'],
         'locaux fonctionnels intégrés': ['salle de réunion',
                                          "salle d'attente",
                                          'cuisine (si intégrée programme tertiaire)',
                                          'salle de repos'],
         'locaux sanitaires (inclus réglementaire)': ['sanitaires', 'w.c.', 'douche'],
         'circulations intégrées sdp': ["hall d'entrée", 'entrée', 'sas', 'dégagements', 'palier', 'circulations'],
         'stockage / annexes intégrées': ['réserve', 'archives', 'local ménage', 'stockage'],
         'locaux techniques inclus (selon réglementation)': ['local serveur',
                                                             'local c.t.a.',
                                                             'onduleur',
                                                             'local sprinkler',
                                                             'r.i.a.',
                                                             'd.a.b.']}}

denom_surf = {'SUB': 'surfaces_utilisables',
 'SU': 'surfaces_utilisables',
 'SUBL': 'surfaces_utilisables',
 'SUN': 'surfaces_utilisables',
 'TAX': 'surfaces_utilisables',
 'TSB': 'surfaces_utilisables',
 'SHO': 'sho',
 'SPD': 'spd',
 'GLA': 'surfaces_utilisables'}

real_su_name = {'SUB': 'SURFACES UTILES BRUTES (SUB*)',
 'SU': 'SURFACES UTILES (SU*)',
 'SUBL': 'SURFACES UTILES BRUTES LOCATIVES (SUBL*)',
 'SUN': 'SURFACES UTILES NETTES (SUN*)',
 'SDP': 'SURFACES DE PLANCHERS (SDP*)',
 'SHO': 'SURFACES HORS OEUVRE (SHO*)',
 'GLA': 'SURFACES GLOBALES (GLA*)',
 'TAX': 'SYNTHESE DES SURFACES RÉELLES* (Art. 324 M ou Z Annexe III du CGI)',
 'SPD': 'SURFACES DE PLANCHERS (SPD*)',
 'TSB': 'TABLEAU SURFACES BRUTES (TSB*)'}
